classdef sam_responseResponse < robotics.ros.Message
    %sam_responseResponse MATLAB implementation of uxa_sam_msgs/sam_responseResponse
    %   This class was automatically generated by
    %   robotics.ros.msg.internal.gen.MessageClassGenerator.
    
    %   Copyright 2016 The MathWorks, Inc.
    
    %#ok<*INUSD>
    
    properties (Constant)
        MessageType = 'uxa_sam_msgs/sam_responseResponse' % The ROS message type
    end
    
    properties (Constant, Hidden)
        MD5Checksum = 'baac1db241f31b1fe6154a3b520ad706' % The MD5 Checksum of the message definition
    end
    
    properties (Access = protected)
        JavaMessage % The Java message object
    end
    
    properties (Dependent)
        Data1
        Data2
    end
    
    properties (Constant, Hidden)
        PropertyList = {'Data1', 'Data2'} % List of non-constant message properties
        ROSPropertyList = {'data1', 'data2'} % List of non-constant ROS message properties
    end
    
    methods
        function obj = sam_responseResponse(msg)
            %sam_responseResponse Construct the message object sam_responseResponse
            import com.mathworks.toolbox.robotics.ros.message.MessageInfo;
            
            % Support default constructor
            if nargin == 0
                obj.JavaMessage = obj.createNewJavaMessage;
                return;
            end
            
            % Construct appropriate empty array
            if isempty(msg)
                obj = obj.empty(0,1);
                return;
            end
            
            % Make scalar construction fast
            if isscalar(msg)
                % Check for correct input class
                if ~MessageInfo.compareTypes(msg(1), obj.MessageType)
                    error(message('robotics:ros:message:NoTypeMatch', obj.MessageType, ...
                        char(MessageInfo.getType(msg(1))) ));
                end
                obj.JavaMessage = msg(1);
                return;
            end
            
            % Check that this is a vector of scalar messages. Since this
            % is an object array, use arrayfun to verify.
            if ~all(arrayfun(@isscalar, msg))
                error(message('robotics:ros:message:MessageArraySizeError'));
            end
            
            % Check that all messages in the array have the correct type
            if ~all(arrayfun(@(x) MessageInfo.compareTypes(x, obj.MessageType), msg))
                error(message('robotics:ros:message:NoTypeMatchArray', obj.MessageType));
            end
            
            % Construct array of objects if necessary
            objType = class(obj);
            for i = 1:length(msg)
                obj(i,1) = feval(objType, msg(i)); %#ok<AGROW>
            end
        end
        
        function data1 = get.Data1(obj)
            %get.Data1 Get the value for property Data1
            data1 = typecast(int8(obj.JavaMessage.getData1), 'uint8');
        end
        
        function set.Data1(obj, data1)
            %set.Data1 Set the value for property Data1
            validateattributes(data1, {'numeric'}, {'nonempty', 'scalar'}, 'sam_responseResponse', 'data1');
            
            obj.JavaMessage.setData1(data1);
        end
        
        function data2 = get.Data2(obj)
            %get.Data2 Get the value for property Data2
            data2 = typecast(int8(obj.JavaMessage.getData2), 'uint8');
        end
        
        function set.Data2(obj, data2)
            %set.Data2 Set the value for property Data2
            validateattributes(data2, {'numeric'}, {'nonempty', 'scalar'}, 'sam_responseResponse', 'data2');
            
            obj.JavaMessage.setData2(data2);
        end
    end
    
    methods (Access = protected)
        function cpObj = copyElement(obj)
            %copyElement Implements deep copy behavior for message
            
            % Call default copy method for shallow copy
            cpObj = copyElement@robotics.ros.Message(obj);
            
            % Create a new Java message object
            cpObj.JavaMessage = obj.createNewJavaMessage;
            
            % Iterate over all primitive properties
            cpObj.Data1 = obj.Data1;
            cpObj.Data2 = obj.Data2;
        end
        
        function reload(obj, strObj)
            %reload Called by loadobj to assign properties
            obj.Data1 = strObj.Data1;
            obj.Data2 = strObj.Data2;
        end
    end
    
    methods (Access = ?robotics.ros.Message)
        function strObj = saveobj(obj)
            %saveobj Implements saving of message to MAT file
            
            % Return an empty element if object array is empty
            if isempty(obj)
                strObj = struct.empty;
                return
            end
            
            strObj.Data1 = obj.Data1;
            strObj.Data2 = obj.Data2;
        end
    end
    
    methods (Static, Access = {?matlab.unittest.TestCase, ?robotics.ros.Message})
        function obj = loadobj(strObj)
            %loadobj Implements loading of message from MAT file
            
            % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = robotics.ros.custom.msggen.uxa_sam_msgs.sam_responseResponse.empty(0,1);
                return
            end
            
            % Create an empty message object
            obj = robotics.ros.custom.msggen.uxa_sam_msgs.sam_responseResponse;
            obj.reload(strObj);
        end
    end
end
